import type { Place } from "../types";

export const SEED_PLACES: Place[] = [
  // --- FOOD ---
  {
    id: "1",
    name: "Pal Dhaba",
    category: "food",
    lat: 30.7046,
    lng: 76.7179,
    city: "mohali",
    budget_level: "low",
    budget_per_person: "₹150–300",
    vibe_tags: ["Foodie", "Budget Backpacker", "Chill"],
    description: "Legendary late-night dhaba near Sector 70. Open till 3 AM, best butter chicken in Mohali. ISB students swear by this place.",
    google_maps_url: "https://maps.google.com/?q=Pal+Dhaba+Mohali",
    distance_from_campus: "12 min drive",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Gopal's Sweets & Restaurant",
    category: "food",
    lat: 30.7333,
    lng: 76.7794,
    city: "chandigarh",
    budget_level: "low",
    budget_per_person: "₹100–250",
    vibe_tags: ["Foodie", "Budget Backpacker"],
    description: "The OG breakfast spot. Chole bhature that'll ruin your diet plans and your heart — in the best way.",
    google_maps_url: "https://maps.google.com/?q=Gopal+Sweets+Chandigarh+Sector+22",
    distance_from_campus: "25 min drive",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Nik Baker's",
    category: "cafe",
    lat: 30.7271,
    lng: 76.7786,
    city: "chandigarh",
    budget_level: "mid",
    budget_per_person: "₹300–600",
    vibe_tags: ["Foodie", "Chill", "Culture Vulture"],
    description: "Best bakery in Chandigarh. Perfect for study brunches, birthday cakes, or when you need carbs after a bad exam.",
    google_maps_url: "https://maps.google.com/?q=Nik+Bakers+Chandigarh",
    distance_from_campus: "22 min drive",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Sector 26 Food Street",
    category: "food",
    lat: 30.7249,
    lng: 76.7904,
    city: "chandigarh",
    budget_level: "low",
    budget_per_person: "₹100–300",
    vibe_tags: ["Foodie", "Budget Backpacker", "Explorer"],
    description: "Chandigarh's street food mecca. Tikki, kulcha, momos, gol gappe. Everything under ₹100. The post-midnight snack destination.",
    google_maps_url: "https://maps.google.com/?q=Sector+26+Market+Chandigarh",
    distance_from_campus: "20 min drive",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Whistling Duck",
    category: "cafe",
    lat: 30.7200,
    lng: 76.8100,
    city: "chandigarh",
    budget_level: "mid",
    budget_per_person: "₹400–800",
    vibe_tags: ["Chill", "Foodie", "Culture Vulture"],
    description: "Cozy cafe with great coffee and amazing ambience. The kind of place where you can read a book or have a long conversation.",
    google_maps_url: "https://maps.google.com/?q=Whistling+Duck+Chandigarh",
    distance_from_campus: "28 min drive",
    created_at: new Date().toISOString(),
  },
  // --- NIGHTLIFE ---
  {
    id: "6",
    name: "F Bar & Lounge",
    category: "nightlife",
    lat: 30.7050,
    lng: 76.8010,
    city: "chandigarh",
    budget_level: "high",
    budget_per_person: "₹1500–3000",
    vibe_tags: ["Party Animal", "Night Owl", "Luxury Seeker"],
    description: "The go-to nightlife spot. Great DJ nights on weekends, decent cocktails. Book a table in advance for Friday/Saturday.",
    google_maps_url: "https://maps.google.com/?q=F+Bar+Chandigarh",
    distance_from_campus: "30 min drive",
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Lemon Tree Hotel Bar",
    category: "nightlife",
    lat: 30.7089,
    lng: 76.6950,
    city: "mohali",
    budget_level: "mid",
    budget_per_person: "₹800–1800",
    vibe_tags: ["Party Animal", "Night Owl", "Chill"],
    description: "Closest decent bar to ISB campus. Great for impromptu weeknight drinks without the long Chandigarh drive.",
    google_maps_url: "https://maps.google.com/?q=Lemon+Tree+Hotel+Mohali",
    distance_from_campus: "15 min drive",
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Bhoot Bangla",
    category: "nightlife",
    lat: 30.7133,
    lng: 76.7977,
    city: "chandigarh",
    budget_level: "mid",
    budget_per_person: "₹1000–2000",
    vibe_tags: ["Party Animal", "Night Owl", "Explorer"],
    description: "Quirky themed bar, always buzzing. Fun vibe, good music, affordable drinks by Chandigarh standards.",
    google_maps_url: "https://maps.google.com/?q=Bhoot+Bangla+Chandigarh",
    distance_from_campus: "27 min drive",
    created_at: new Date().toISOString(),
  },
  // --- TRAVEL / WEEKEND TRIPS ---
  {
    id: "9",
    name: "Kasauli Weekend",
    category: "travel",
    lat: 30.8980,
    lng: 76.9660,
    city: "kasauli",
    budget_level: "mid",
    budget_per_person: "₹2000–4000",
    vibe_tags: ["Explorer", "Chill", "Budget Backpacker"],
    description: "The classic ISB weekend escape. 1.5 hrs from campus, colonial charm, great walks through the monkey point trail. Book Baikunth resort early.",
    google_maps_url: "https://maps.google.com/?q=Kasauli+Himachal+Pradesh",
    distance_from_campus: "1.5 hr drive",
    created_at: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Shimla Express Trip",
    category: "travel",
    lat: 31.1048,
    lng: 77.1734,
    city: "shimla",
    budget_level: "mid",
    budget_per_person: "₹3000–6000",
    vibe_tags: ["Explorer", "Culture Vulture", "Budget Backpacker"],
    description: "Ideal 2-day trip. The Mall Road, Jakhu Temple, and snow in winter. Best done as a group of 6-8 with a rented tempo traveller.",
    google_maps_url: "https://maps.google.com/?q=Shimla+Himachal+Pradesh",
    distance_from_campus: "3 hr drive",
    created_at: new Date().toISOString(),
  },
  {
    id: "11",
    name: "Dharamshala & McLeod Ganj",
    category: "travel",
    lat: 32.2190,
    lng: 76.3234,
    city: "dharamshala",
    budget_level: "mid",
    budget_per_person: "₹4000–8000",
    vibe_tags: ["Explorer", "Culture Vulture", "Chill"],
    description: "3-day trip worthy of the MBA experience. Dalai Lama temple, cricket stadium, amazing cafes. The \"spiritual reset\" every ISB student needs.",
    google_maps_url: "https://maps.google.com/?q=McLeod+Ganj+Dharamshala",
    distance_from_campus: "5 hr drive",
    created_at: new Date().toISOString(),
  },
  {
    id: "12",
    name: "Manali Long Weekend",
    category: "travel",
    lat: 32.2432,
    lng: 77.1892,
    city: "manali",
    budget_level: "mid",
    budget_per_person: "₹6000–12000",
    vibe_tags: ["Explorer", "Party Animal", "Budget Backpacker"],
    description: "The bucket list trip. 3 nights, Solang Valley, Rohtang (if open), riverside bonfires. Best in long weekends with a solid group.",
    google_maps_url: "https://maps.google.com/?q=Manali+Himachal+Pradesh",
    distance_from_campus: "7 hr drive",
    created_at: new Date().toISOString(),
  },
  {
    id: "13",
    name: "Sukhna Lake Panchkula",
    category: "travel",
    lat: 30.7480,
    lng: 76.8120,
    city: "panchkula",
    budget_level: "low",
    budget_per_person: "₹200–500",
    vibe_tags: ["Chill", "Explorer", "Budget Backpacker"],
    description: "Quick 30-min escape. Sunrise walks, paddle boating, chai. The decompression spot for weekday evenings.",
    google_maps_url: "https://maps.google.com/?q=Sukhna+Lake+Chandigarh",
    distance_from_campus: "30 min drive",
    created_at: new Date().toISOString(),
  },
  {
    id: "14",
    name: "Rock Garden Chandigarh",
    category: "travel",
    lat: 30.7500,
    lng: 76.8050,
    city: "chandigarh",
    budget_level: "low",
    budget_per_person: "₹100–200",
    vibe_tags: ["Culture Vulture", "Explorer", "Chill"],
    description: "Nek Chand's outsider art masterpiece. Genuinely unique, worth one visit. Sunday morning with chai after is the move.",
    google_maps_url: "https://maps.google.com/?q=Rock+Garden+Chandigarh",
    distance_from_campus: "28 min drive",
    created_at: new Date().toISOString(),
  },
  // --- CAFE ---
  {
    id: "15",
    name: "Elma's Bakery & Kitchen",
    category: "cafe",
    lat: 30.7350,
    lng: 76.7910,
    city: "chandigarh",
    budget_level: "mid",
    budget_per_person: "₹400–700",
    vibe_tags: ["Foodie", "Chill", "Culture Vulture"],
    description: "Chandigarh's most Instagrammable cafe. Great for meetings, dates, or when you need to feel productive outside campus.",
    google_maps_url: "https://maps.google.com/?q=Elma+Bakery+Chandigarh",
    distance_from_campus: "25 min drive",
    created_at: new Date().toISOString(),
  },
];
